### PR TITLE
Compression plugin

### LINKED ISSUE #183: Compression plugin
See https://news.ycombinator.com/item?id=13753527

### PR DESCRIPTION
**Pull request by w33ble**
Closes #183 

- Adds a compression plugin, which uses `get` and `set` directly
- Users can opt out of compression using an extra argument, ex) `store.get('key', true)`, `store.set('key', 'value', true)`
- Adds `lz-string` to `plugins/lib`
- Simple compress and decompress tests

This is pretty simple. I'm not sure how I should be handling namespacing, or if I even need to.

### CODE REVIEW

**Comment by marcuswestin** [comment]
Super cool!! First v2 community plugin :)

Yes, the whole super_fn stuff is not super intuitive and a bit opaque. I'm looking for a better alternative if you can think of one.

super_fn has a property which is an array of the arguments that will be passed on. You can modify that array. I think I called it "args" but would have to check. 

Maybe if super_fn receives arguments it should pass on those instead. The potential issue is if there are other plugins in between which accept more arguments than the original implementation, such as expire - I went with the current approach to ensure that they would always be passed on properly.

Let me know how it goes and if you have thoughts on this!

**Comment by w33ble** [comment]
Yeah, I saw the args thing when I was debugging it. Originally, I assumed that `super_fn` just took the arguments you want, so i was calling `super_fn(key, compressed)` in set, and then when I saw it running, it was set to the uncompressed value. I was going nuts trying to figure out what I did wrong, until I dug a little deeper ;)

Let me tinker, I'm thinking I can just make it override the arguments passed into `super_fn` and fall back to whatever was originally went in.

**Comment by w33ble** [comment]
@marcuswestin rebased on master, and updated to use the get/set methods. I added an extra `raw` argument, so that even if the compression plugin is enabled, users can manually opt out when getting and setting data. It was also handy for the tests.

**Comment by marcuswestin** [comment]
Nice!

At this point multiple plugins with custom arguments don't work together :/ I think we may need to rethink optional args and plugins with custom args... Shouldn't block this PR though.

Will take a look tomorrow - it's 7p and I need to feed the baby :)

**Comment by w33ble** [comment]
I can remove that `raw` argument if you'd like. I started writing it as additional methods, and I could go back to doing it that way.

**Comment by w33ble** [comment]
Was this waiting on me for anything?

**Comment by marcuswestin** [comment]
No, it's waiting for me. Sorry @w33ble. Life happened :) I'll be taking this on in coming days.

**Comment by w33ble** [comment]
That's fine. Hope all is ok!

I'll be honest, I've kind of lost interest in this PR. Figured it was better to close it than leaving it linger and worry about future updates. You're welcome to take it on, or use your own approach. I won't be offended if you don't use my commits ;).

**Comment by marcuswestin** [comment]
This has been released in v2.0.11. I only had to make some small changes to bring up to date and make tests pass for legacy IE browsers.

Thank you again @w33ble!

**Comment by mstralka** [comment]
This is cool but it should be noted that it causes errors if users already had data stored from an older version of storejs, and you add the compress plugin.

My app was using `store/dist/store.everything.min.js`, which includes all of the plugins automatically. When I updated from 2.0.4 to 2.0.11 and loaded the app in a browser that already had data in storage, it immediately threw this stack trace:
```
app.js:sourcemap:83912 Uncaught TypeError: t.charCodeAt is not a function
    at https://localhost/js/app.js:83912:10572
    at Object._decompress (https://localhost/js/app.js:83912:10671)
    at Object.decompress (https://localhost/js/app.js:83912:10524)
    at Object.t (https://localhost/js/app.js:83912:1373)
    at Object.(anonymous function) (https://localhost/js/app.js:83912:14911)
    at e (https://localhost/js/app.js:83912:14847)
    at Object.e (https://localhost/js/app.js:83912:1658)
    at Object.(anonymous function) (https://localhost/js/app.js:83912:14911)
    at e (https://localhost/js/app.js:83912:14847)
    at Object.e (https://localhost/js/app.js:83912:3139)
```

Loading the app in Chrome Incognito did not have this error.

My workaround was to switch to `store/dist/store.modern.min.js`

**Comment by marcuswestin** [comment]
Good point Mark - the compression read should probably have a fall back.
Will take a look.
