### ISSUE TITLE
v2 failed in PhantomJS

### ISSUE THREAD

**Issue by rokoroku** [marcuswestin/store.js#220]
prior to v2, my tests are all good. but after upgrading to v2, `store` related tests are all broken now.

using `karma@1.5`, `karma-phantomjs-launcher@1.0.4`, `phantomjs@2.1.1` and `webpack@2.2.1`

is this problem related to phantomJS's missing support for localstorage? 

example output:
```
FAILED TESTS:
  AuthStore
    ✖ "before all" hook
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    undefined is not a constructor (evaluating '__WEBPACK_IMPORTED_MODULE_2_app_utils__["a" /* LocalStorage */].clear()')
    test/app/stores/AuthStore.spec.ts:108701:78

    ✖ "after all" hook
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    undefined is not a constructor (evaluating '__WEBPACK_IMPORTED_MODULE_2_app_utils__["a" /* LocalStorage */].clear()')
    test/app/stores/AuthStore.spec.ts:108704:78
```

**Comment by rokoroku** [comment]
It resolves with using  `require('store/dist/store.everything.min')`  or  `require('store/dist/store.legacy.min')`. 

Why don't we use `main` entry in `package.json` to direct distribution build?, or we can add `browser` entry to the `package.json`. It will prevent such situations.

**Comment by rokoroku** [comment]
Found that it caused by deprecated `clear()` method. 
Changing it to clearAll() resolves the issues :)

**Comment by BelinChung** [comment]
`store.js`  failed in PhantomJS@2.1
Here is the error log
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not a function (evaluating 'this._deserialize(data, optionalDefaultValue)')
  at webpack:///node_modules/store/src/store-engine.js:23:0 <- index.js:154778
```
Is there any way to solve the problem?
